version: "3.9"
services:
  worker:
    build: .
    environment:
      APP_ID: $API_ID
      API_HASH: $API_HASH
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      OWNER_ID: $OWNER_ID
      DATABASE_URL: $DATABASE_URL
      
